In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans: The datatypes of variable of the list is "string" and the datatype of the variable of the array_list is "numpy.str_".

dtype='<U1' is "a little-endian 1 character string or unicode." 

In [14]:
def datatype1(x):
    if type(x)==list:
        return type(list_[0])
    return x.dtype

In [15]:
datatype1(array_list)

dtype('<U1')

datatype1(list_)

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [23]:
def datatype1(x):
    list1=[]
    for i in x:
        list1.append(type(i))
    return list1

In [24]:
datatype1(array_list)

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

In [26]:
datatype1(list_)

[str, str, str, str, str]

Q3. Considering the following changes in the variable, array_list:
    
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [28]:
array_list = np.array(object = list_, dtype = int)

In [29]:
array_list

array([1, 2, 3, 4, 5])

In [30]:
list_

['1', '2', '3', '4', '5']

Yes, there is a difference. The datatype of the list_ is "string" and the datatype of the array_list is integers now.

In [31]:
def datatype1(x):
    list1=[]
    for i in x:
        list1.append(type(i))
    return list1

In [32]:
datatype1(array_list)

[numpy.int64, numpy.int64, numpy.int64, numpy.int64, numpy.int64]

In [33]:
datatype1(list_)

[str, str, str, str, str]

In [34]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [35]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [46]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [37]:
num_array.shape

(2, 3)

In [38]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])