In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import joblib 
import pandas as pd

In [20]:
class perceptron:
    # weight get initialized here
    def __init__(self,eta,epochs):
        self.weights=np.random.randn(3)* 1e-4
        print(f"Weights are:{self.weights}")
        self.eta=eta
        self.epochs=epochs
       
    # here w1*x1 + w2*x2 + w3*x3 + ---- + Wn*xn will be calculated 
    def activation_function(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z>0,1,0) # weights will get updated according to the threshold we sets 
    
    # here weights get updated Wnew = Wold - (alpha * xi * [partial diff of loss / partial diff of weights])
    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]                                   # dot product 
        print(f"X_with_bias \n {X_with_bias}") # w1*x1+w2*x2+w3*x3+b can be written as [x1 x2 x3 1].[w1 w2 w3 b]
        
        for epochs in range(self.epochs):
            print(f"for epoch: {epochs}")
            y_hat=self.activation_function(X_with_bias,self.weights)
            print(f"predicted value: \n{y_hat}")
            error=self.y-y_hat
            print(f"Error is: \n{error}")
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T,error)
            print(f"Updated weights is: {self.weights}")
            
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones((len(self.X),1))]   # concatenate
        return self.activation_function(X_with_bias,self.weights)

### AND Operation

In [5]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}

In [7]:
AND=pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [8]:
X=AND.drop('y',axis=1)

In [9]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [10]:
y=AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [28]:
model=perceptron(eta=0.5,epochs=10)
model.fit(X,y)

Weights are:[-1.04467759e-04  2.39560565e-05 -5.64355858e-05]
X_with_bias 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 0 0]
Error is: 
0   -1
1   -1
2    0
3    1
Name: y, dtype: int64
Updated weights is: [4.99895532e-01 2.39560565e-05 4.99943564e-01]
for epoch: 1
predicted value: 
[0 0 0 0]
Error is: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights is: [ 9.99895532e-01  5.00023956e-01 -5.64355858e-05]
for epoch: 2
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights is: [4.99895532e-01 2.39560565e-05 1.49994356e+00]
for epoch: 3
predicted value: 
[0 0 0 0]
Error is: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights is: [0.99989553 0.50002396 0.99994356]
for epoch: 4
predicted value: 
[0 0 0 1]
Error is: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights is: [0.99989553 0.50002396 0.99994356]
for epoch: 5
predicted value: 
[0 0 0 1

In [29]:
model.predict(X)

array([0, 0, 0, 1])

In [30]:
model.weights

array([0.99989553, 0.50002396, 0.99994356])

### OR Operation

In [31]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]}

In [32]:
OR=pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [35]:
X=OR.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [39]:
y=OR['y']
y.to_frame()  # perfrom dataframe operation on top of y 

y
0  0
1  1
2  1
3  1

In [40]:
model=perceptron(eta=0.5,epochs=10)
model.fit(X,y)

Weights are:[-4.73816528e-05 -1.91728829e-05 -1.62038867e-04]
X_with_bias 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights is: [-4.73816528e-05 -1.91728829e-05  4.99837961e-01]
for epoch: 1
predicted value: 
[0 0 0 0]
Error is: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights is: [ 0.99995262  0.99998083 -1.00016204]
for epoch: 2
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights is: [ 0.99995262  0.99998083 -0.50016204]
for epoch: 3
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights is: [ 9.99952618e-01  9.99980827e-01 -1.62038867e-04]
for epoch: 4
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights is: [0.99995262 0.99998083 0.49983796]
for epoch: 5
predicted value: 
[0 1 1 1]
E

In [41]:
model.predict(X)

array([0, 1, 1, 1])

In [42]:
model.weights

array([0.99995262, 0.99998083, 0.49983796])

### XOR function

In [44]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,0]}

In [45]:
XOR=pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [46]:
X=XOR.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [47]:
y=XOR['y']
y.to_frame()

y
0  0
1  1
2  1
3  0

In [50]:
model=perceptron(eta=0.5,epochs=100)
model.fit(X,y)

Weights are:[1.47901018e-04 2.42714321e-05 1.56841482e-04]
X_with_bias 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 1]
Error is: 
0    0
1    1
2    1
3   -1
Name: y, dtype: int64
Updated weights is: [ 1.47901018e-04  2.42714321e-05 -4.99843159e-01]
for epoch: 1
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights is: [-0.4998521  -0.49997573  0.50015684]
for epoch: 2
predicted value: 
[0 0 0 0]
Error is: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights is: [ 1.47901018e-04  2.42714321e-05 -4.99843159e-01]
for epoch: 3
predicted value: 
[1 1 1 1]
Error is: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights is: [-0.4998521  -0.49997573  0.50015684]
for epoch: 4
predicted value: 
[0 0 0 0]
Error is: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights is: [ 1.47901018e-04  2.42714321e-05 -4.99843159e-01]
for epoch: 5
predicted value: 

### Observation
XOR Function is not predicting correct output even after 100 epochs.But why?

Reasons: As we are using only perceptron here and the activation function is also very simple(thresholding function)

In [51]:
model.predict(X)   # wrong predictions 

array([0, 0, 0, 0])