### 1) One hot Encoder

In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [2]:
# create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [4]:
# create an instance of one hot encoder
encoder=OneHotEncoder()

In [6]:
# perform fit and transform 
encoder.fit_transform(df[['color']])   # it will create sparse matrix

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [8]:
encoded=encoder.fit_transform(df[['color']]).toarray()  # sort accor. alphabetically order

In [9]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [10]:
import pandas as pd
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoded_df   # this way convert categorical feature into numerical feature

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [13]:
encoder.transform([['blue']]).toarray()   # new data should be from red blue or green

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoded_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

### 2) Label encoder

In [15]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [17]:
from sklearn.preprocessing import LabelEncoder
lab_encod=LabelEncoder()

In [18]:
lab_encod.fit_transform(df[['color']])  # sorted in alphabetical order

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [21]:
lab_encod.transform([['green']])# new datapoints 

array([1])

#### Disadvantage of label encoder: 
a unique value is get assign with every datapoints. here, red is assign with 2 , blue with 0,green with 1.
Our model will consider that red is greater than green and blue. But we dont assign rank in such categorical values. 

### 3) Ordinal encoder

In [ ]:
# we can assign ranks in this ordinal encoding 

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
df=pd.DataFrame({
    "size":['small','medium','large','medium','small','large']
})

In [27]:
df.head()

size
0   small
1  medium
2   large
3  medium
4   small

In [30]:
ord_encod=OrdinalEncoder(categories=[['small','medium','large']])  # lower to higher rank

In [31]:
ord_encod.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [34]:
ord_encod.transform([['medium']]) # new data

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])