### Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### we will take  sepal length in cm,sepal width in cm,petal length in cm,petal width in cm as independent variable and then predict the dependent variable (class)

### We will train a model using binary classification to predict  (Iris-Setosa or Iris-Versicolour) only these 2 values . Later we will do model training for multiclass classification.

In [4]:
dataset.keys()   # these are all the key points

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import pandas as pd 
import numpy as np

In [6]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

#### This dataframe contains only the independent variables or data, we will later add one more column which is class or target value. That column contain the numerical values Iris-Setosa: 0 , Iris-Versicolour: 1 and Iris-Virginica:2

In [7]:
print(dataset.target)    # 150 datapoint

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
# add the target column into dataframe 
df['target']=dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df['target'].unique()

array([0, 1, 2])

in binary we have only 2 categories so we will convert the current target into 2 categories only 

We will remove the category 2 and then split the data into train and validation using train test split and then do the model training

In [12]:
df_copy=df[df['target']!=2]

In [13]:
df_copy['target'].unique()   # only 1 and 0 is in the target 

array([0, 1])

In [14]:
from sklearn.model_selection import train_test_split

In [34]:
# independent features
x=df_copy.iloc[:,:-1]  # take all columns just subtract the last column
# dependent feature 
y=df_copy.iloc[:,-1] # just take the last column 

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

### Apply logistic regression

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
classification=LogisticRegression(max_iter=200) #create logistic reg. using default parameter, later we will use different parameter 

In [38]:
classification

LogisticRegression(max_iter=200)

In [39]:
classification.fit(x_train,y_train)  
# without the max_iter it will give us some warning. So change max_iter from 100 to 200.
# why it is giving this error because it is unable to reach on global minima
# on that iteration value it was unable to find different theta 0 and theta 1 value 

LogisticRegression(max_iter=200)

In [40]:
y_pred=classification.predict(x_test)

In [41]:
y_pred  # prediction is  0 and 1 only

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

### accuracy , confusion matrix , classification report (precision and recall)

In [42]:
# in linear we find accuracy by r square and adjusted r square
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [44]:
print(confusion_matrix(y_test,y_pred))  # there is no false positive or false negative

[[12  0]
 [ 0  8]]


In [47]:
print(accuracy_score(y_test,y_pred))   # gives 100 % accuracy

1.0


In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
# cross validation can be done internally during the train test and split of thr dataset.
# Because of the random state if we keep on changing then we get the separate train and test data.
# so that we cna perform hyper parameter tunning

In [52]:
from sklearn.model_selection import KFold

In [53]:
cv=KFold(n_splits=5,shuffle=True) # shuffle the data before doing every spliting of data into the train and test 

In [54]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [ ]:
#apply logistic regression considering cross validation,get various accuracy.we do this split for hyperparameter tunning 

In [55]:
from sklearn.model_selection import cross_val_score

In [59]:
# use logistic regression object and divide the x_train and y_train into train and validation data to calculate accuracy
scores=cross_val_score(classification,x_train,y_train,scoring='accuracy',cv=cv) # scoring should be accuracy keyword
# these produce the score of the 5 experiment

In [60]:
# final score
np.mean(scores)

1.0

In [61]:
# lets take another example to find cross validation with more complex data
# make a prediction wtih a multinominal linguistic regression model 
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=1)

In [62]:
# we have made dataset using make_classification

In [63]:
from sklearn.model_selection import train_test_split 

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [65]:
complex_class_model=LogisticRegression(max_iter=200)

In [66]:
complex_class_model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [68]:
y_pred_complex=complex_class_model.predict(x_test)

In [71]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [75]:
# improve the accuracy with cross validation
cv=KFold(n_splits=5)
cross_val_score(complex_class_model,x_train,y_train,cv=cv)  # 80.9%

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])