In [1]:
import numpy as np

In [6]:
arr1=np.random.randint(1,5,(4,4))

In [7]:
arr1

array([[1, 1, 2, 2],
       [2, 1, 2, 4],
       [3, 3, 2, 1],
       [2, 1, 2, 1]])

#### Array manupulation

In [8]:
arr1.reshape(8,2)

array([[1, 1],
       [2, 2],
       [2, 1],
       [2, 4],
       [3, 3],
       [2, 1],
       [2, 1],
       [2, 1]])

In [9]:
# Transpose (rotate the entire array by 180')
arr1.T

array([[1, 2, 3, 2],
       [1, 1, 3, 1],
       [2, 2, 2, 2],
       [2, 4, 1, 1]])

In [ ]:
#Flatten : Put all the data in 1-D array

In [11]:
arr1.flatten()

array([1, 1, 2, 2, 2, 1, 2, 4, 3, 3, 2, 1, 2, 1, 2, 1])

In [ ]:
# Expand dimension (increment dimension)

In [12]:
np.expand_dims(arr1)

TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'

In [15]:
np.expand_dims(arr1,axis=1)   #Expand D columnwise

array([[[1, 1, 2, 2]],

       [[2, 1, 2, 4]],

       [[3, 3, 2, 1]],

       [[2, 1, 2, 1]]])

In [16]:
np.expand_dims(arr1,axis=0)   #Expand D rowwise

array([[[1, 1, 2, 2],
        [2, 1, 2, 4],
        [3, 3, 2, 1],
        [2, 1, 2, 1]]])

In [ ]:
# squeeze function from larger dimension to one lower dimension

In [17]:
arr2=np.array([[1],[2],[3]])   

In [18]:
arr2

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(arr2)  #From 2 D to 1 D

array([1, 2, 3])

In [21]:
# repeat function
np.repeat(arr2,2) # repeat the data of the array 2 times

array([1, 1, 2, 2, 3, 3])

In [ ]:
# ROll function: it roll the data in circular form for a specified no of times

In [23]:
np.roll(arr2,1) # last index comes first 

array([[3],
       [1],
       [2]])

In [24]:
np.roll(arr2,2) # last index comes first after 2 rolls 

array([[2],
       [3],
       [1]])

In [25]:
np.roll(arr2,3) # last index comes first after 3 rolls 

array([[1],
       [2],
       [3]])

In [ ]:
#diag function: It takes 1-D data as an argument and then place the element of that array on the diagonal of 2-D array 

In [27]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### Binary Operation : +,-,*,/,**,%,!,>,<,>=,<=,!=,==

In [29]:
arr3=np.random.randint(1,10,(4,5))

In [28]:
arr4=np.random.randint(1,10,(4,5))

In [30]:
arr3

array([[5, 5, 3, 2, 9],
       [2, 5, 4, 3, 8],
       [1, 5, 7, 6, 5],
       [1, 5, 1, 4, 2]])

In [31]:
arr4

array([[6, 2, 9, 9, 3],
       [1, 8, 9, 3, 6],
       [2, 3, 8, 1, 4],
       [4, 3, 3, 3, 7]])

In [33]:
arr3**arr4  #power 

array([[  15625,      25,   19683,     512,     729],
       [      2,  390625,  262144,      27,  262144],
       [      1,     125, 5764801,       6,     625],
       [      1,     125,       1,      64,     128]])

In [35]:
-arr3

array([[-5, -5, -3, -2, -9],
       [-2, -5, -4, -3, -8],
       [-1, -5, -7, -6, -5],
       [-1, -5, -1, -4, -2]])

In [37]:
arr3>arr4

array([[False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True, False,  True,  True],
       [False,  True, False,  True, False]])

#### String function : Every function of the string is simliar to the numpy.char class 

In [38]:
arr6=np.array(["Deepa","Pooja","Shivangi","Aman","Sachin"])

In [39]:
arr6

array(['Deepa', 'Pooja', 'Shivangi', 'Aman', 'Sachin'], dtype='<U8')

In [42]:
np.char.upper(arr6)   #uppercase

array(['DEEPA', 'POOJA', 'SHIVANGI', 'AMAN', 'SACHIN'], dtype='<U8')

In [44]:
np.char.title(arr6) 

array(['Deepa', 'Pooja', 'Shivangi', 'Aman', 'Sachin'], dtype='<U8')

In [45]:
np.char.capitalize(arr6)   #Capitalize and title are similar

array(['Deepa', 'Pooja', 'Shivangi', 'Aman', 'Sachin'], dtype='<U8')

#### Mathematical function

In [48]:
arr3

array([[5, 5, 3, 2, 9],
       [2, 5, 4, 3, 8],
       [1, 5, 7, 6, 5],
       [1, 5, 1, 4, 2]])

In [49]:
#Determine the sinosoidal value of every thing 
np.sin(arr3)

array([[-0.95892427, -0.95892427,  0.14112001,  0.90929743,  0.41211849],
       [ 0.90929743, -0.95892427, -0.7568025 ,  0.14112001,  0.98935825],
       [ 0.84147098, -0.95892427,  0.6569866 , -0.2794155 , -0.95892427],
       [ 0.84147098, -0.95892427,  0.84147098, -0.7568025 ,  0.90929743]])

In [50]:
np.tan(arr3)

array([[-3.38051501, -3.38051501, -0.14254654, -2.18503986, -0.45231566],
       [-2.18503986, -3.38051501,  1.15782128, -0.14254654, -6.79971146],
       [ 1.55740772, -3.38051501,  0.87144798, -0.29100619, -3.38051501],
       [ 1.55740772, -3.38051501,  1.55740772,  1.15782128, -2.18503986]])

In [53]:
np.log10(arr3)

array([[0.69897   , 0.69897   , 0.47712125, 0.30103   , 0.95424251],
       [0.30103   , 0.69897   , 0.60205999, 0.47712125, 0.90308999],
       [0.        , 0.69897   , 0.84509804, 0.77815125, 0.69897   ],
       [0.        , 0.69897   , 0.        , 0.60205999, 0.30103   ]])

In [54]:
np.exp(arr3)

array([[1.48413159e+02, 1.48413159e+02, 2.00855369e+01, 7.38905610e+00,
        8.10308393e+03],
       [7.38905610e+00, 1.48413159e+02, 5.45981500e+01, 2.00855369e+01,
        2.98095799e+03],
       [2.71828183e+00, 1.48413159e+02, 1.09663316e+03, 4.03428793e+02,
        1.48413159e+02],
       [2.71828183e+00, 1.48413159e+02, 2.71828183e+00, 5.45981500e+01,
        7.38905610e+00]])

In [55]:
np.power(arr3,3)

array([[125, 125,  27,   8, 729],
       [  8, 125,  64,  27, 512],
       [  1, 125, 343, 216, 125],
       [  1, 125,   1,  64,   8]])

In [56]:
np.mean(arr3)

4.15

In [57]:
np.median(arr3)

4.5

In [59]:
np.std(arr3)

2.242208732477866

In [60]:
np.var(arr3)

5.0275

In [61]:
np.min(arr3)

1

In [62]:
np.max(arr3)

9

#### Arithmetic operation

In [63]:
arr3

array([[5, 5, 3, 2, 9],
       [2, 5, 4, 3, 8],
       [1, 5, 7, 6, 5],
       [1, 5, 1, 4, 2]])

In [64]:
arr4

array([[6, 2, 9, 9, 3],
       [1, 8, 9, 3, 6],
       [2, 3, 8, 1, 4],
       [4, 3, 3, 3, 7]])

In [65]:
arr3-arr4

array([[-1,  3, -6, -7,  6],
       [ 1, -3, -5,  0,  2],
       [-1,  2, -1,  5,  1],
       [-3,  2, -2,  1, -5]])

In [66]:
np.subtract(arr3,arr4)   #Just the same function as above

array([[-1,  3, -6, -7,  6],
       [ 1, -3, -5,  0,  2],
       [-1,  2, -1,  5,  1],
       [-3,  2, -2,  1, -5]])

In [67]:
np.multiply(arr3,arr4)

array([[30, 10, 27, 18, 27],
       [ 2, 40, 36,  9, 48],
       [ 2, 15, 56,  6, 20],
       [ 4, 15,  3, 12, 14]])

In [69]:
np.mod(arr3,arr4)

array([[5, 1, 3, 2, 0],
       [0, 5, 4, 0, 2],
       [1, 2, 7, 0, 1],
       [1, 2, 1, 1, 2]])

In [70]:
np.power(arr3,arr4)

array([[  15625,      25,   19683,     512,     729],
       [      2,  390625,  262144,      27,  262144],
       [      1,     125, 5764801,       6,     625],
       [      1,     125,       1,      64,     128]])

In [72]:
np.sqrt(arr3)

array([[2.23606798, 2.23606798, 1.73205081, 1.41421356, 3.        ],
       [1.41421356, 2.23606798, 2.        , 1.73205081, 2.82842712],
       [1.        , 2.23606798, 2.64575131, 2.44948974, 2.23606798],
       [1.        , 2.23606798, 1.        , 2.        , 1.41421356]])

#### Statistical function :mean, mode, median, sd, var, min, max