#### Sort ,count and search function

In [1]:
import numpy as np 

In [12]:
arr1=np.array([4,3,7,6,8,1,9])

In [13]:
arr1

array([4, 3, 7, 6, 8, 1, 9])

In [14]:
np.sort(arr1)

array([1, 3, 4, 6, 7, 8, 9])

In [15]:
#Searchsorted :Find indices where elements should be inserted to maintain order.
np.searchsorted(arr1,5)

2

In [18]:
#Count function
arr2=np.array([0,0,21,4,0,0,6,76,0,0,58,0])

In [19]:
arr2

array([ 0,  0, 21,  4,  0,  0,  6, 76,  0,  0, 58,  0])

In [20]:
np.count_nonzero(arr2)

5

In [22]:
#Where: it gives indices of element to be search
np.where(arr2>6)

(array([ 2,  7, 10]),)

In [24]:
#extract : filter the data 
np.extract(arr2>5,arr2)

array([21,  6, 76, 58])

#### Byte swapping: represent the data in byte

In [25]:
arr2

array([ 0,  0, 21,  4,  0,  0,  6, 76,  0,  0, 58,  0])

In [26]:
arr2.byteswap()

array([                  0,                   0, 1513209474796486656,
        288230376151711744,                   0,                   0,
        432345564227567616, 5476377146882523136,                   0,
                         0, 4179340454199820288,                   0])

In [28]:
arr2  #The above operation is not permanent

array([ 0,  0, 21,  4,  0,  0,  6, 76,  0,  0, 58,  0])

In [29]:
arr2.byteswap(True)

array([                  0,                   0, 1513209474796486656,
        288230376151711744,                   0,                   0,
        432345564227567616, 5476377146882523136,                   0,
                         0, 4179340454199820288,                   0])

In [30]:
arr2   #Now it become permanent (just like inplace =True)

array([                  0,                   0, 1513209474796486656,
        288230376151711744,                   0,                   0,
        432345564227567616, 5476377146882523136,                   0,
                         0, 4179340454199820288,                   0])

#### Copies and views

In [32]:
arr1

array([4, 3, 7, 6, 8, 1, 9])

In [35]:
a=np.copy(arr1)  # deep copy

In [36]:
a

array([4, 3, 7, 6, 8, 1, 9])

In [37]:
b=arr1.view()  #shallow copy  (just like b == arr1)

In [38]:
b

array([4, 3, 7, 6, 8, 1, 9])

In [39]:
b[2]=50

In [40]:
b

array([ 4,  3, 50,  6,  8,  1,  9])

In [41]:
arr1

array([ 4,  3, 50,  6,  8,  1,  9])

#### Matrix Library

In [42]:
import numpy.matlib as nm   # matlib is matrix library

In [44]:
nm.zeros(5)  # gives 2-D array

matrix([[0., 0., 0., 0., 0.]])

In [45]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
nm.eye(4)    #identity matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

#### linear algebra 

In [53]:
arr1=np.random.randint([[2,3],[5,4]])

In [54]:
arr2=np.random.randint([[5,3],[2,5]])

In [55]:
arr1

array([[0, 0],
       [0, 2]])

In [56]:
arr2

array([[1, 1],
       [0, 2]])

In [57]:
# Dot product of these 2 arrays
np.dot(arr1,arr2)

array([[0, 0],
       [0, 4]])

In [58]:
# The dot product is actually the matrix multiplication
arr1@arr2   #Same result 

array([[0, 0],
       [0, 4]])